### ISSUE TITLE
Only exports first seven sources unless sidebar is expanded

### ISSUE THREAD

**Issue by waxpancake** [skogard/SOPML#1]
By default, Substack Reader only shows up to seven subscriptions in the sidebar, unless you expand it, and then it shows them all. If you try to use the bookmarklet before clicking the "Show XX More" button, it only exports an OPML with seven sources. 

![image](https://user-images.githubusercontent.com/6759/102407687-51d30300-3fa1-11eb-963e-f6f1e13ce240.png)

After expanding the sidebar, it adds an .expanded class to both div.sidebar-publications-container and div.sidebar-expand-list. Is it possible to look for that .expanded class, and if it doesn't exist, expand the sidebar to retrieve all the sources before doing the export?

**Comment by skogard** [comment]
This has been resolved by auto-clicking the "show more" before running the logic https://github.com/skogard/SOPML/commit/9c8a79319601231ab6cebbfec9335dedd4f544f6#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R62

I don't have that many subscriptions so I confirm it works for around 14 subscriptions, but let me know if it works for 47 too.

**Comment by waxpancake** [comment]
It works! I have 54 and it exported them all. Thanks for the quick fix, this is great!
